#!/bin/sh
#PBS -l nodes=1:ppn=1,mem=46gb
#PBS -l walltime=50:00:00
#PBS -j oe
#PBS -m abe
#PBS -V
#PBS -M begumtop@umich.edu
#PBS -q fluxod
#PBS -l qos=flux
#PBS -A pschloss_fluxod

echo "ncpus-2.pbs"
cat $PBS_NODEFILE
qstat -f $PBS_JOBID

cd $PBS_O_WORKDIR

NCPUS=`wc -l $PBS_NODEFILE | awk '{print $1}'`

mothur code/cluster_after_clustersplit.batch

echo "qsub working directory absolute is"
echo $PBS_O_WORKDIR
exit
